VENDOR=xiaomi
DEVICE=mione_plus
OUTDIR=vendor/$VENDOR/$DEVICE
MAKEFILE=../../../$OUTDIR/$DEVICE-vendor-blobs.mk

(cat << EOF) > $MAKEFILE
# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh

# Linkable audio blobs are declared in Android.mk.
PRODUCT_PACKAGES += libaudioalsa libacdbloader libacdbmapper libnv liboncrpc

# Other prebuilt libraries needed during linking
PRODUCT_COPY_FILES += \\
	$OUTDIR/proprietary/vendor/lib/libv8.so:obj/lib/libv8.so

PRODUCT_COPY_FILES += \\
EOF

LINEEND=" \\"
COUNT=`wc -l proprietary-files.txt | awk {'print $1'}`
DISM=`egrep -c '(^#|^$)' proprietary-files.txt`
COUNT=`expr $COUNT - $DISM`
for FILE in `egrep -v '(^#|^$)' proprietary-files.txt`; do
  case "$FILE" in
    vendor/lib/libaudioalsa.so|vendor/lib/libacdbloader.so|vendor/lib/libacdbmapper.so|vendor/lib/libstlport.so|vendor/lib/libnv.so|vendor/lib/liboncrpc.so|vendor/lib/libaudcal.so|vendor/lib/libdiag.so|vendor/lib/libdsm.so|vendor/lib/libqueue.so)
      COUNT=`expr $COUNT - 1`
      continue
      ;;
  esac
  COUNT=`expr $COUNT - 1`
  if [ $COUNT = "0" ]; then
    LINEEND=""
  fi
  DEST="\$(TARGET_COPY_OUT_VENDOR)/${FILE#vendor/}"
  echo "  $OUTDIR/proprietary/$FILE:$DEST$LINEEND" >> $MAKEFILE
done

(cat << EOF) > ../../../$OUTDIR/$DEVICE-vendor.mk
# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh

# Pick up overlay for features that depend on non-open-source files
DEVICE_PACKAGE_OVERLAYS := vendor/$VENDOR/$DEVICE/overlay

\$(call inherit-product, vendor/$VENDOR/$DEVICE/$DEVICE-vendor-blobs.mk)
EOF

(cat << EOF) > ../../../$OUTDIR/BoardConfigVendor.mk
# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh
EOF



cat > ../../../$OUTDIR/Android.mk <<'MIONE_PREBUILT_MK'
# Copyright (C) 2026 The LineageOS Project
# SPDX-License-Identifier: Apache-2.0

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),mione_plus)

include $(CLEAR_VARS)
LOCAL_MODULE := libaudioalsa
LOCAL_MODULE_OWNER := xiaomi
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := proprietary/vendor/lib/libaudioalsa.so
LOCAL_VENDOR_MODULE := true
LOCAL_STRIP_MODULE := false
LOCAL_CXX_STL := none
LOCAL_SHARED_LIBRARIES := libc libstdc++ libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libacdbloader
LOCAL_MODULE_OWNER := xiaomi
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := proprietary/vendor/lib/libacdbloader.so
LOCAL_VENDOR_MODULE := true
LOCAL_STRIP_MODULE := false
LOCAL_CXX_STL := none
# The old ARM blob imports libcrt symbols hidden from the public libc stub.
# Check against the implementation, which exports these as LIBC_PRIVATE.
LOCAL_SHARED_LIBRARIES := libcutils libutils liblog libaudcal libc.bootstrap libstdc++ libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libacdbmapper
LOCAL_MODULE_OWNER := xiaomi
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := proprietary/vendor/lib/libacdbmapper.so
LOCAL_VENDOR_MODULE := true
LOCAL_STRIP_MODULE := false
LOCAL_CXX_STL := none
LOCAL_SHARED_LIBRARIES := libcutils libutils liblog libaudioalsa libc libstdc++ libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libstlport
LOCAL_MODULE_OWNER := xiaomi
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := proprietary/vendor/lib/libstlport.so
LOCAL_VENDOR_MODULE := true
LOCAL_STRIP_MODULE := false
LOCAL_CXX_STL := none
LOCAL_SHARED_LIBRARIES := libc libm libstdc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnv
LOCAL_MODULE_OWNER := xiaomi
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := proprietary/vendor/lib/libnv.so
LOCAL_VENDOR_MODULE := true
LOCAL_STRIP_MODULE := false
LOCAL_CXX_STL := none
LOCAL_SHARED_LIBRARIES := liboncrpc libdiag libc libstdc++ libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := liboncrpc
LOCAL_MODULE_OWNER := xiaomi
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := proprietary/vendor/lib/liboncrpc.so
LOCAL_VENDOR_MODULE := true
LOCAL_STRIP_MODULE := false
LOCAL_CXX_STL := none
LOCAL_SHARED_LIBRARIES := libcutils libutils libdsm libqueue libdiag liblog libc libstdc++ libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libaudcal
LOCAL_MODULE_OWNER := xiaomi
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := proprietary/vendor/lib/libaudcal.so
LOCAL_VENDOR_MODULE := true
LOCAL_STRIP_MODULE := false
LOCAL_CXX_STL := none
LOCAL_SHARED_LIBRARIES := libutils liblog libdiag libacdbmapper libc libstdc++ libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libdiag
LOCAL_MODULE_OWNER := xiaomi
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := proprietary/vendor/lib/libdiag.so
LOCAL_VENDOR_MODULE := true
LOCAL_STRIP_MODULE := false
LOCAL_CXX_STL := none
# The old ARM blob imports libcrt symbols hidden from the public libc stub.
# Check against the implementation, which exports these as LIBC_PRIVATE.
LOCAL_SHARED_LIBRARIES := libc.bootstrap libstdc++ libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libdsm
LOCAL_MODULE_OWNER := xiaomi
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := proprietary/vendor/lib/libdsm.so
LOCAL_VENDOR_MODULE := true
LOCAL_STRIP_MODULE := false
LOCAL_CXX_STL := none
# The old ARM blob imports libcrt symbols hidden from the public libc stub.
# Check against the implementation, which exports these as LIBC_PRIVATE.
LOCAL_SHARED_LIBRARIES := libqueue libdiag libc.bootstrap libstdc++ libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libqueue
LOCAL_MODULE_OWNER := xiaomi
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := proprietary/vendor/lib/libqueue.so
LOCAL_VENDOR_MODULE := true
LOCAL_STRIP_MODULE := false
LOCAL_CXX_STL := none
LOCAL_SHARED_LIBRARIES := libc libstdc++ libm
include $(BUILD_PREBUILT)

include $(LOCAL_PATH)/prebuilt/webview/Android.mk

endif
MIONE_PREBUILT_MK
