devices {
    dir = "/dev"
    scan = [ "/dev/block" ]
    preferred_names = [ "^/dev/block/mmcblk0p" ]
    filter = [ "a|^/dev/block/mmcblk0p15$|", "a|^/dev/block/mmcblk0p20$|", "r|.*|" ]
    write_cache_state = 0
    obtain_device_list_from_udev = 0
    sysfs_scan = 1
    md_component_detection = 0
}
activation {
    udev_sync = 0
    udev_rules = 0
    verify_udev_operations = 0
    monitoring = 0
    volume_list = [ "mione" ]
}
global {
    locking_type = 1
    locking_dir = "/dev/mione-lvm/lock"
    use_lvmetad = 0
}
backup {
    backup = 1
    backup_dir = "/dev/mione-lvm/backup"
    archive = 1
    archive_dir = "/dev/mione-lvm/archive"
}
log { syslog = 0 }
